version: "3.7"

services:
  codam-web-greeter-server:
    container_name: codam-web-greeter-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
      - ./messages.json:/app/messages.json
    env_file:
      - .env
    # exposes port 3000 on the container from the Dockerfile

  nginx:
    container_name: codam-web-greeter-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/certs:/etc/nginx/certs
    depends_on:
      - codam-web-greeter-server
